### ISSUE TITLE
Suggestion: debuff to Magnifying lens for realism

### ISSUE THREAD

**Issue by d4n13lus-com** [ttr/tld-fireAddons#3]
Hi! Its possible to put an option in the mod menu to configurable debuff for mag lens? (like lantern)

would be nice for realism, starting a fire with mag lens would be difficult for a "newbie" (low fire skill level)
and an option for a very very little degradation on use for this item too, like 0,1-0,2% decay on use.

thanks and very good work!

**Comment by ttr** [comment]
debuff will be easy. degradation is bit different as it's not on each use - it's more of "if it's triggered it will decay by x". Will have a look.

**Comment by d4n13lus-com** [comment]
thanks ttr! your work it's very appreciated
this mod is one of my favorites, make the game much better! =D

**Comment by ttr** [comment]
fixed in v1.8.0
