### ISSUE TITLE
Woodstove unuseable without hover text

### ISSUE THREAD

**Issue by emmaliefje** [ttr/tld-fireAddons#4]
I am having an issue that I can no longer use the woodstove in Milton House because the hover text does not appear, which makes it impossible to light a fire and use the stove. Melon-loader attributes it to an issue in Fire Addons. 
[Latest.log](https://github.com/ttr/tld-fireAddons/files/6719839/Latest.log)

**Comment by ttr** [comment]
Hey, can you provide me with screenshoots of issue.

**Comment by ttr** [comment]
Also, does it still happen with only FireAddons (and ModSettings) loaded - I see you have other Fire modification mods that can create issue.

**Comment by ttr** [comment]
![image](https://user-images.githubusercontent.com/1327295/123508163-a1d40600-d665-11eb-81fc-235024cd8cb2.png)
and no stacktrace in logs.

**Comment by emmaliefje** [comment]
Hi, thanks for getting back to me so quickly. 
I am using FirePack and FireImprovements. I was able to use the stove once. The next time, my fire failed and the hover text disappeared. I was able to save-scum out of the issue twice, and had the same bug three times, but save-scumming the third time did not fix the bug (it stayed, even though I hadn't lit a fire that 'day').  I have not tested whether other stoves also have this issue. 
I will test if removing the other mods fixes the issue.
![screen_650f9fe5-ccf8-407c-90c4-d75857678fd0](https://user-images.githubusercontent.com/52350900/123508405-83730800-d66f-11eb-9d28-3d64f54dc428.png)

**Comment by emmaliefje** [comment]
After removing the other fire mods, the hover text did not reappear on the stove (within the same save file), and the melon-loader continued to show the same errors.
[Latest.log](https://github.com/ttr/tld-fireAddons/files/6719869/Latest.log)

**Comment by ttr** [comment]
ok, will need to see if issue is with new version of melon loader.

**Comment by emmaliefje** [comment]
FYI, I've just had the same bug in the stove in Trapper's Homestead. I was able to save-scum out of it to fix it, but since I'm planning on making Trapper's Homestead my base, I'm very hesitant to keep going. Hoping you can find a fix!
[Latest.log](https://github.com/ttr/tld-fireAddons/files/6720466/Latest.log)

**Comment by ttr** [comment]
This is weird.
On New melon is still works fine for me.
Does this happens to Campfire? And also, what are your language/locale settings - perhaps this is down to language actually.

If I'll not be able to trace this, I'll add option to disable hovercard update so they will be default (no 2nd timer).

**Comment by emmaliefje** [comment]
Hi! So far it hasn't happened to campfire (I've made about 15 of them), but has happened 80% of the time in 6- or 2-top stoves. I've been playing without fire-addons (but with my other fire mods) for about 7 hours now and haven't had the bug reappear, so I'm fairly sure it is the mod. I play in English and have never changed anything in the language settings, everything is on default.

**Comment by Commenterry** [comment]
This issue is happening to me as well, but it only happens if I fail to make a fire on a particular stove. After the failure, I cannot use the stove again.

**Comment by ttr** [comment]
OK, I have so little of time to even scratch my bottom that i did not test this, BUT that lead me to believe where this NPE is coming out.
Can you try this version and tell me if this is happening?
[FireAddons.zip](https://github.com/ttr/tld-fireAddons/files/7007357/FireAddons.zip)

**Comment by Commenterry** [comment]
That didn't fix it for me. What's worse, is that even if I remove the mod, I still can't use the stove in question. The issue seems baked into my save. In any event, I loaded a different sandbox and failed at a stove and it made it unusable.

**Comment by ttr** [comment]
If you removed my mod, than issue is not coming from it - saved state is saved in save but in separate to vanilla data and it's reloaded on each scene change - so if you removed my mod non of it's functionality is applied.

**Comment by ttr** [comment]
OK, issue looks to be in my mod, but this is in hover-card display - disabling it makes fire object working.
Still, not sure how issue persist for you if you removed my mod.

**Comment by ttr** [comment]
even better - removing code about hovercards still cause stacktrace and same issue.

**Comment by ttr** [comment]
`NullReferenceException: Object reference not set to an instance of an object.
  at WoodStove.FireBurningInside () [0x00000] in <00000000000000000000000000000000>:0 
  at WoodStove.GetHoverText () [0x00000] in <00000000000000000000000000000000>:0 
  at PlayerManager.GetInteractiveObjectDisplayText (UnityEngine.GameObject interactiveObject) [0x00000] in <00000000000000000000000000000000>:0 
  at PlayerManager.UpdateHUDText () [0x00000] in <00000000000000000000000000000000>:0 
  at PlayerManager.Update () [0x00000] in <00000000000000000000000000000000>:0 `

This is w/o Hovercard - seems that functionality of how FireBurningInside changed and now my mod is causing issues.

Will mark mod as unstable.

**Comment by ttr** [comment]
Fix on a way

**Comment by ttr** [comment]
v1.8.1 released.

**Comment by Commenterry** [comment]
Thank you!
